### ISSUE TITLE
Add arrival support to whitecane_rfduino.ino

### ISSUE THREAD

**Issue by craighiller** [SynthSense/whitecane#1]
To indicate arrival, we should define a new haptic pattern in the nav band. This could be accomplished by  adding two new functions `void navband_vibrate_left_arrive(void)` and `void navband_vibrate_left_arrive(void)` with similar content to the non-arrival versions, except right after the loop have something like 

``` pin_set(0);
delay(50);
pin_set(end_motor);
delay(50);
pin_set(0);
delay(50);
pin_set(end_motor);
delay(50);
pin_set(0);
```

Where `end_motor` is either the first or last motor on the band. The timings and specific pattern are open to experimentation, but I think that this would be a good starting point.

Additional support  would be needed in `void RFduinoBLE_onReceive(char *data, int len)` for checking if `data[0] == 2` (left arrive) or if `data[0]==3` (right arrive).

In the future, there should be a way to communicate the patterns from the phone to the RFduino, but that seems like a v2 feature.

**Comment by adithyamurali** [comment]
Resolved, let's test before soldering
